import { useState } from "react";
import Query from "../../General/Query.jsx";
import { Code } from "@mantine/core";
import { server, type } from "../../../Services/api.js";

const Add = ({ table, tableHeadFields, tableFields }) => {
	//TODO: Add color button
	const title = "Add Type";
	const [jsonData, setJsonData] = useState(
		JSON.stringify({
			name: "Noun",
			status: "A",
		}),
	);
	const urlDefault = `${server}${type.add.url}`;
	const urlMethod = type.add.method;
	console.log(urlDefault, urlMethod, jsonData);
	const shortDetails = `The API provides a POST /type method that allows adding a new 
	record to the type table. The data for the new type must be sent in the request body 
	in JSON format, including all required attributes except for the idType field, which 
	is auto-generated by the system and does not need to be provided. Additionally, if the 
	request includes a password field, it will be encrypted before being stored in the 
	database to ensure security. This endpoint is designed for creating new types, 
	enabling seamless integration with systems or user interfaces that require dynamic 
	data management. Upon successful creation, the API returns a confirmation response 
	along with the details of the newly added type.`;

	const note = () => <></>;
	const example = () => <></>;

	return (
		<Query
			title={title}
			keyUnique={`${table}${urlDefault}`}
			jsonData={jsonData}
			setJsonData={setJsonData}
			urlDefault={urlDefault}
			urlMethod={urlMethod}
			shortDetails={shortDetails}
			note={note}
			example={example}
			tableFields={tableFields}
			tableHeadFields={tableHeadFields}
		/>
	);
};

export default Add;
