import { useState } from "react";
import Query from "../../General/Query.jsx";
import { Code } from "@mantine/core";
import { server, user } from "../../../Services/api.js";

const Add = ({ table, tableHeadFields, tableFields }) => {
	//TODO: Add color button
	const title = "Add User";
	const [jsonData, setJsonData] = useState(
		JSON.stringify({
			firstName: "Jefferson",
			lastName: "Miranda",
			user: "jmiranda",
			password: "3456hnfDFKgv",
			email: "jmiranda@mail.com",
			status: "A",
			gender: "M",
		}),
	);
	const urlDefault = `${server}${user.add.url}`;
	const urlMethod = user.add.method;
	console.log(urlDefault, urlMethod, jsonData);
	const shortDetails = `The API provides a POST /user method that allows adding a new record 
	to the user table. The data for the new user must be sent in the request body in JSON format, 
	including all required attributes except for the idUser field, which is auto-generated by the 
	system and does not need to be provided. Additionally, the password field will be securely 
	encrypted before being stored in the database. This endpoint is designed for creating new 
	user accounts, ensuring seamless integration with systems or user interfaces that require 
	dynamic user management. Upon successful creation, the API returns a confirmation response 
	along with the details of the newly added user.`;

	const note = () => <></>;
	const example = () => <></>;

	return (
		<Query
			title={title}
			keyUnique={`${table}${urlDefault}`}
			jsonData={jsonData}
			setJsonData={setJsonData}
			urlDefault={urlDefault}
			urlMethod={urlMethod}
			shortDetails={shortDetails}
			note={note}
			example={example}
			tableFields={tableFields}
			tableHeadFields={tableHeadFields}
		/>
	);
};

export default Add;
